 ALTER TABLE DEPOSITE ADD CITY VARCHAR(20),PINCODE INT
 SELECT * FROM DEPOSITE

 ALTER TABLE DEPOSITE ALTER COLUMN CITY VARCHAR(35)
 SELECT * FROM DEPOSITE

 ALTER TABLE DEPOSITE  ALTER COLUMN AMOUNT INT
  SELECT * FROM DEPOSITE

 SP_RENAME 'DEPOSITE.ACTNO' ,'ANO'
 SELECT * FROM DEPOSITE

 ALTER TABLE DEPOSITE DROP COLUMN CITY
 SELECT * FROM DEPOSITE

 SP_RENAME 'DEPOSITE' , 'DEPOSITE_DETAIL'
 SELECT * FROM DEPOSITE_DETAIL

 --PART-B

 SP_RENAME 'DEPOSITE_DETAIL.ADATE','AOPENDATE'
 SELECT * FROM DEPOSITE_DETAIL

 ALTER TABLE DEPOSITE_DETAIL DROP COLUMN AOPENDATE
  SELECT * FROM DEPOSITE_DETAIL

  SP_RENAME 'DEPOSITE_DETAIL.CNAME','CUSTOMERSNAME'
 SELECT * FROM DEPOSITE_DETAIL


 CREATE TABLE STUDENT_DETAIL(
    ENROLLMENT_NO VARCHAR(20),
	NAME VARCHAR(25),
	CPI DECIMAL(5,2),
	BIRTHDATE DATETIME
)

SELECT * FROM STUDENT_DETAIL

ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(20)NOT NULL,BACKLOG INT
SELECT * FROM STUDENT_DETAIL

ALTER TABLE STUDENT_DETAIL ALTER COLUMN  NAME VARCHAR(35)
SELECT * FROM STUDENT_DETAIL

ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT
SELECT * FROM STUDENT_DETAIL

SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO'
 SELECT * FROM STUDENT_DETAIL

 ALTER TABLE  STUDENT_DETAIL DROP COLUMN CITY
 SELECT * FROM STUDENT_DETAIL

 SP_RENAME 'STUDENT_DETAIL' , 'STUDENT_MASTER'
 SELECT * FROM STUDENT_MASTER

 

 --DELETE

--PART-A

DELETE FROM DEPOSITE_DETAIL WHERE  AMOUNT>=4000
SELECT * FROM DEPOSITE_DETAIL


DELETE FROM DEPOSITE_DETAIL WHERE BNAME='CHANDI'
SELECT * FROM DEPOSITE_DETAIL

DELETE FROM DEPOSITE_DETAIL WHERE ANO>105
SELECT * FROM DEPOSITE_DETAIL

TRUNCATE TABLE DEPOSITE_DETAIL 

DROP TABLE DEPOSITE_DETAIL 



CREATE TABLE EMPLOYEE_MASTER(
    EMP INT,
	EMPNAME VARCHAR(25),
	JOININGDATE DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
) 

INSERT INTO EMPLOYEE_MASTER VALUES(101,'KEYUR','1995-1-5',12000,'RAJKOT'),
								  (102,'Hardik','2004-2-15',14000,'AHMEDABAD'),
								  (103,'KEYUR','2006-3-14',15000,'BARODA'),
								  (104, 'Bhoomi','2005-6-23',12500.00,'Ahmedabad'),
								  (105,'Harmit','2004-2-15',14000,'RAJKOT'),
								  (106,'MITESH','2001-9-25',5000,'Jamnagar'),
								  (107,'MEERA',NULL,7000,'Morbi'),
								  (108,'KISHAN','2003-2-6',10000,Null)
								  SELECT * FROM EMPLOYEE_MASTER

 DELETE FROM EMPLOYEE_MASTER WHERE  SALARY >= 14000
 SELECT * FROM EMPLOYEE_MASTER

 DELETE FROM EMPLOYEE_MASTER WHERE  CITY='RAJKOT'

 DELETE FROM EMPLOYEE_MASTER WHERE  JOININGDATE>='2007-1-1'

 --DELETE FROM EMPLOYEE_MASTER WHERE JOININGDATE IS NULL

 DELETE FROM EMPLOYEE_MASTER WHERE SALARY=(20000*0.5)

 DELETE FROM EMPLOYEE_MASTER WHERE  CITY IS NOT NULL

 TRUNCATE TABLE EMPLOYEE_MASTER

 DROP TABLE EMPLOYEE_MASTER